global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "app"
    static_configs: [{ targets: ["app:8080"] }]
  - job_name: "postgres-exporter"
    static_configs: [{ targets: ["postgres-exporter:9187"] }]
  - job_name: "node-exporter"
    static_configs: [{ targets: ["node-exporter:9100"] }]
