version: "3.8"

services:

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      ENV: "DOCKER" # PROD # DOCKER
      PORT: 8080
      DATABASE_URL: "db:5432"
      DATABASE_USER: "postgres"
      DATABASE_PASS: "admin"
      DATABASE_NAME: "postgres"
    depends_on:
      - db

  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      # POSTGRES_USER: root # postgres
      # POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      #- ./data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
