
GET http://localhost:9999
###

GET http://localhost:9999/ping
###

GET http://localhost:9999/health
###

POST http://localhost:9999/v1/person
Content-Type: application/json
X-Idempotency-Key: {{$guid}}

{
    "name": "Person {{$guid}}"
}
###

GET http://localhost:9999/v1/person/b3c27563-dd72-46da-a5d7-bdfb996822b6
###

GET http://localhost:9999/v1/person
###

PUT http://localhost:9999/v1/person/b3c27563-dd72-46da-a5d7-bdfb996822b6
Content-Type: application/json

{
    "name": "Novo João da Silva"
}
###

DELETE http://localhost:9999/v1/person/b3c27563-dd72-46da-a5d7-bdfb996822b6
###

GET http://localhost:9999/v1/person/count
###
