services:
  redis:
    image: redis:8.2.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --appendonly no --maxclients 20000 --maxmemory 32mb --maxmemory-policy allkeys-lru --loglevel warning
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4.1.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    command: rabbitmq-server
    ports:
      - "5552:5552"
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=secretcookie
    networks:
      - backend

networks:
  backend:
    driver: bridge
