global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9999"]
      # - targets: ["localhost:9999"]
      # - targets: ["host.docker.internal:9999"]
      # - targets: ["otel-collector:8889"]

  # - job_name: "otel-collector"
  #   static_configs:
  #     - targets: ["otel-collector:8889"]
  # - job_name: "tempo"
  #   static_configs:
  #     - targets: ["tempo:3200"]
