version: "3.9"

services:

  wrk-cotacao-golang:
    container_name: wrk-cotacao-golang
    image: "cms-tnb-cotacao-golang:latest"
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
