receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:

extensions:
  health_check: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otel"

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
