global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    metrics_path: /metrics
    static_configs:
      # - targets: ["localhost:8889"]
      - targets: ["otel-collector:8889"]
