global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9090"]

  # - job_name: prometheus
  #   static_configs:
  #     - targets: ["localhost:9090"]

  # - job_name: myapp
  #   metrics_path: /metrics
  #   follow_redirects: true
  #   static_configs:
  #     - targets: ["nginx:9999"]
