---
global:
  scrape_interval: 5s # Por padrão, o Prometheus raspa seus alvos a cada 15 segundos.
  scrape_timeout: 5s
  evaluation_interval: 5s # A frequência com que as regras são avaliadas.
  external_labels:
    monitor: 'my-project'

alerting:

rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

scrape_configs:
- job_name: api01  # Define um trabalho chamado 'api01'.
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  shceme: http
  follow_redirects: true
  static_configs:
  - targets: # ["api01:8081"] # A direção do alvo a ser raspado.
    - api01:8081
