

USE CMS_TESTE_JDSPB;


SELECT COUNT(1) FROM TBUSUARIO WITH(NOLOCK);
-- DELETE FROM TBUSUARIO;


---------------------------------------------------------------------------------
---------------------------------------------------------------------------------



/*


SELECT ID, NOME, STATUS FROM TBUSUARIO WITH(NOLOCK) ORDER BY NOME;


select isNull(SCOPE_IDENTITY(), -1);


-- delete from TBUSUARIO where id = '1774FED7-B68B-494F-A9C4-CB81F2319AD3';
-- delete from TBUSUARIO where id = '481CB4FF-089E-4B0C-A9B5-2FA59FBE6C0E';
SELECT ID, NOME, STATUS FROM TBUSUARIO WITH(NOLOCK) WHERE NOME LIKE 'NOVA PESSOA%';
SELECT ID, NOME, STATUS FROM TBUSUARIO WITH(NOLOCK) WHERE NOME LIKE '%Teste%';


DROP TABLE TBUSUARIO;
CREATE TABLE TBUSUARIO( ID UNIQUEIDENTIFIER NOT NULL  PRIMARY KEY, NOME VARCHAR(100) NOT NULL , STATUS CHAR (1) NOT NULL );


DELETE FROM TBUSUARIO;
INSERT INTO TBUSUARIO (ID, NOME, STATUS) VALUES (NEWID(), 'PESSOA 1', 'A');
INSERT INTO TBUSUARIO (ID, NOME, STATUS) VALUES (NEWID(), 'PESSOA 2', 'A');
INSERT INTO TBUSUARIO (ID, NOME, STATUS) VALUES (NEWID(), 'PESSOA 3', 'A');



*/