version: "3.5"

services:

  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    restart: always
    environment:
      - PORT=":3001"
      - DATABASE_DRIVER="postgres"
      - DATABASE_URL="host=db port=5432 dbname=postgres user=postgres password=postgres sslmode=disable"
      - DATABASE_MAX_CONNECTIONS="100"
      - MENSAGEM="Teste via Docker Compose - api01"
    ports:
      - "3001:8080"
  
  # db:
  #   image: postgres:latest
  #   hostname: db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #     - POSTGRES_USER=admin
  #     - POSTGRES_DB=rinha
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./script.sql:/docker-entrypoint-initdb.d/script.sql
  #     - ./postgres.conf:/etc/postgresql/postgresql.conf
  #     - ./data:/var/lib/postgresql/data
  #   command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  #   # network_mode: host
  #   # deploy:
  #     # resources:
  #       # limits:
  #         # cpus: "0.8"
  #         # memory: "2.5GB"

  # api01: &api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   hostname: api01
  #   restart: always
  #   environment:
  #     - PORT=":3001"
  #     - DATABASE_DRIVER="postgres"
  #     - DATABASE_URL="host=db port=5432 dbname=postgres user=postgres password=postgres sslmode=disable"
  #     - DATABASE_MAX_CONNECTIONS="100"
  #     - MENSAGEM="Teste via Docker Compose - api01"
  #   ports:
  #     - "3001:8080"
  #   depends_on:
  #     - db
  #   # network_mode: host
  #   # deploy:
  #     # resources:
  #       # limits:
  #         # cpus: "0.3"
  #         # memory: "350MB"

  # api02:
  #   <<: *api 
  #   hostname: api02
  #   environment:
  #     - PORT=":3000"
  #     - DATABASE_DRIVER="postgres"
  #     - DATABASE_URL="host=db port=5432 dbname=postgres user=postgres password=postgres sslmode=disable"
  #     - DATABASE_MAX_CONNECTIONS="100"
  #     - MENSAGEM="Teste via Docker Compose - api02"
  #   ports:
  #     - "3002:8080"
  #   # network_mode: host
  #   # deploy:
  #     # resources:
  #       # limits:
  #         # cpus: "0.3"
  #         # memory: "350MB"

  # nginx:
  #   image: nginx:latest  # nginx:1.21.6-alpine
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "9999:9999" 
  #   #network_mode: host
  #   depends_on:
  #     - api01
  #     - api02
  #   # deploy:
  #     # resources:
  #       # limits:
  #         # cpus: "0.1"
  #         # memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
